# Generated by Django 4.0.3 on 2022-12-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faj', models.CharField(choices=[('kutya', 'Kutya'), ('cica', 'Cica'), ('egyeb', 'Egyeb')], default='kutya', max_length=200)),
                ('meret', models.CharField(choices=[('kicsi', 'Kicsi'), ('kozepes', 'Kozepes'), ('nagy', 'Nagy')], default='kicsi', max_length=200)),
                ('ivar', models.CharField(choices=[('fiu', 'Fiu'), ('lany', 'Lany')], default='fiu', max_length=200)),
                ('nev', models.CharField(max_length=200)),
                ('bekerulesideje', models.DateField()),
                ('szuletesiideje', models.DateField()),
                ('ivartalanitva', models.BooleanField()),
                ('leiras', models.TextField()),
                ('eletkor', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hirek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=200)),
                ('tartalom', models.TextField()),
                ('hir_main_img', models.ImageField(upload_to='app_menhely/img/photos')),
            ],
        ),
        migrations.CreateModel(
            name='AllatMainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_menhely/img/photos/')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_menhely/img/thumbs/')),
                ('allat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menhely.allat')),
            ],
        ),
        migrations.CreateModel(
            name='AllatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_menhely/img/photos/')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_menhely/img/thumbs/')),
                ('allat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menhely.allat')),
            ],
        ),
    ]
