# Generated by Django 4.0.3 on 2024-04-22 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faj', models.CharField(choices=[('kutya', 'kutya'), ('cica', 'cica'), ('egyeb', 'egyéb')], default='kutya', max_length=200, verbose_name='kutya/cica')),
                ('meret', models.CharField(choices=[('kicsi', 'kistestű'), ('kozepes', 'közepes testű'), ('nagy', 'nagytestű')], default='kicsi', max_length=200, verbose_name='méret')),
                ('ivar', models.CharField(choices=[('fiu', 'fiú'), ('lany', 'lány')], default='fiu', max_length=200, verbose_name='ivar')),
                ('nev', models.CharField(max_length=200, verbose_name='név')),
                ('szuletesiideje', models.DateField()),
                ('ivartalanitva', models.BooleanField()),
                ('leiras', models.TextField(default='Leírás később érkezik. Amennyiben a képek alapján érdeklődnél, keress facebook messengeren vagy telefonon.')),
                ('eletkor', models.IntegerField(blank=True, editable=False, null=True)),
                ('orokbeadva', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Állat',
                'verbose_name_plural': 'Állatok',
            },
        ),
        migrations.CreateModel(
            name='Bemutatkozas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemutatkozas_main_img', models.ImageField(upload_to='app_menhely/img/photos')),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Bemutatkozó szöveg',
                'verbose_name_plural': 'Bemutatkozó szöveg',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hirek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hir_main_img', models.ImageField(default='/app_menhely/hiralap.jpg', upload_to='app_menhely/img/photos')),
                ('hir_main_img_tumb', models.ImageField(default='/app_menhely/hiralap.jpg', editable=False, upload_to='app_menhely/img/thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hír',
                'verbose_name_plural': 'Hírek',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Kapcsolat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Kapcsolat',
                'verbose_name_plural': 'Kapcsolat',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Kimutatasok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Kimutatás',
                'verbose_name_plural': 'Kimutatások',
            },
        ),
        migrations.CreateModel(
            name='AllatMainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_menhely/img/photos/', verbose_name='kiemelt kép')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_menhely/img/thumbs/')),
                ('allat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menhely.allat')),
            ],
            options={
                'verbose_name': 'Kiemelt kép',
                'verbose_name_plural': 'Kiemelt kép',
            },
        ),
        migrations.CreateModel(
            name='AllatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_menhely/img/photos/', verbose_name='galéria kép')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_menhely/img/thumbs/')),
                ('allat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menhely.allat')),
            ],
            options={
                'verbose_name': 'Galéria kép',
                'verbose_name_plural': 'Galéria képek',
            },
        ),
        migrations.CreateModel(
            name='KapcsolatTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('telefonszam', models.CharField(max_length=50)),
                ('nyitvatartashp', models.CharField(max_length=50)),
                ('nyitvatartassz', models.CharField(max_length=50)),
                ('nyitvatartasv', models.CharField(max_length=50)),
                ('emailcim', models.CharField(default='', max_length=50)),
                ('telephely', models.CharField(default='', max_length=50)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_menhely.kapcsolat')),
            ],
            options={
                'verbose_name': 'Kapcsolat Translation',
                'db_table': 'app_menhely_kapcsolat_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HirekTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('cim', models.CharField(max_length=200)),
                ('tartalom', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_menhely.hirek')),
            ],
            options={
                'verbose_name': 'Hír Translation',
                'db_table': 'app_menhely_hirek_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BemutatkozasTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('cim', models.CharField(max_length=200)),
                ('tartalom', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_menhely.bemutatkozas')),
            ],
            options={
                'verbose_name': 'Bemutatkozó szöveg Translation',
                'db_table': 'app_menhely_bemutatkozas_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
