# Generated by Django 4.0.3 on 2022-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menhely', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allat',
            name='eletkor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
