# Generated by Django 4.0.3 on 2022-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menhely', '0003_bemutatkozas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allat',
            name='faj',
            field=models.CharField(choices=[('kutya', 'Kutya'), ('cica', 'Cica'), ('egyéb', 'Egyeb')], default='kutya', max_length=200, verbose_name='faj'),
        ),
        migrations.AlterField(
            model_name='allat',
            name='ivar',
            field=models.CharField(choices=[('fiú', 'Fiu'), ('lány', 'Lany')], default='fiu', max_length=200),
        ),
        migrations.AlterField(
            model_name='allat',
            name='meret',
            field=models.CharField(choices=[('kicsi', 'Kicsi'), ('közepes', 'Kozepes'), ('nagy', 'Nagy')], default='kicsi', max_length=200, verbose_name='méret'),
        ),
    ]
