# Generated by Django 4.0.3 on 2022-12-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menhely', '0004_alter_allat_faj_alter_allat_ivar_alter_allat_meret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allat',
            name='faj',
            field=models.CharField(choices=[('kutya', 'kutya'), ('cica', 'cica'), ('egyeb', 'egyéb')], default='kutya', max_length=200, verbose_name='kutya/cica'),
        ),
        migrations.AlterField(
            model_name='allat',
            name='ivar',
            field=models.CharField(choices=[('fiu', 'fiú'), ('lany', 'lány')], default='fiu', max_length=200, verbose_name='ivar'),
        ),
        migrations.AlterField(
            model_name='allat',
            name='meret',
            field=models.CharField(choices=[('kicsi', 'kistestű'), ('kozepes', 'közepes testű'), ('nagy', 'nagytestű')], default='kicsi', max_length=200, verbose_name='méret'),
        ),
        migrations.AlterField(
            model_name='allat',
            name='nev',
            field=models.CharField(max_length=200, verbose_name='név'),
        ),
    ]
