# Generated by Django 4.0.3 on 2022-12-28 14:49

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menhely', '0006_remove_hirek_cim_remove_hirek_tartalom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='cim',
        ),
        migrations.RemoveField(
            model_name='bemutatkozas',
            name='tartalom',
        ),
        migrations.CreateModel(
            name='BemutatkozasTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('cim', models.CharField(max_length=200)),
                ('tartalom', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_menhely.bemutatkozas')),
            ],
            options={
                'verbose_name': 'bemutatkozas Translation',
                'db_table': 'app_menhely_bemutatkozas_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
