# Generated by Django 4.0.3 on 2022-12-29 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_menhely', '0007_remove_bemutatkozas_cim_remove_bemutatkozas_tartalom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hirek',
            name='hir_main_img_tumb',
            field=models.ImageField(default='app_menhely/images/bg.jpg', editable=False, upload_to='app_menhely/img/thumbs/'),
        ),
        migrations.AddField(
            model_name='hirek',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
